version: "3.1"

services:
  api:
    build:
      target: base
      context: .
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/rdb
    networks:
      - net
    volumes:
      - .:/api
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: pnpm dev

  db:
    image: postgres
    environment:
      POSTGRES_DB: rdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - net
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  net:
    driver: bridge

volumes:
  pg-data:
