name: API

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/api.yaml'
      - 'api/**'

defaults:
  run:
    working-directory: api

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: deps-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6
          run_install: true

      - name: Lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: deps-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6
          run_install: true

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
        run: pnpm test:coverage
