name: App

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/app.yaml'
      - 'app/**'

defaults:
  run:
    working-directory: app

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PUB_CACHE: ~/.pub-cache

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.PUB_CACHE }}
          key: deps-${{ hashFiles('**/pubspec.lock') }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Get packages
        run: |
          echo $PUB_CACHE
          flutter pub get

      - name: Run tests
        run: flutter test
